[scrolling]
history = 10000 
multiplier = 3

[font]
normal = {family = "FiraCode Nerd Font Mono",  style = "Regular"}
bold = {family = "FiraCode Nerd Font Mono",  style = "Bold"}
italic = {family = "FiraCode Nerd Font Mono",  style = "Italic"}
bold_italic = {family = "FiraCode Nerd Font Mono",  style = "Bold Italic"}

size = 11.25

[window]
decorations = "Full"
opacity = 0.9
